title: Sexy-AllpAcks
description: Equipo de CTF Peruano
email: staff@sexy-allpacks.com
logo: images/logo.png
baseurl: ""
url: "https://sexy-allpacks.github.io/"

# Redes Sociales
twitter: 'https://twitter.com/sexy_allpacks'
github: 'https://github.com/sexy-allpacks'
ctftime: 'https://ctftime.org/'
